# Generated by Django 5.2 on 2025-04-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите телеграм чат-id', null=True,
                                   verbose_name='Телеграм чат-id'),
        ),
    ]
