# Generated by Django 5.2 on 2025-04-10 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('habits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='habits',
            name='award',
            field=models.ForeignKey(blank=True, help_text='Вознаграждение', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='habits.award'),
        ),
        migrations.AddField(
            model_name='habits',
            name='related_habit',
            field=models.ForeignKey(blank=True, help_text='Связанная привычка', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='habits.habits'),
        ),
        migrations.AddField(
            model_name='habits',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='owner_lesson',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
