# Generated by Django 5.2 on 2025-04-11 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='sign_of_publicity',
            new_name='is_public',
        ),
    ]
