# Generated by Django 5.2 on 2025-04-12 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('habits', '0003_rename_sign_of_publicity_habits_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='pleasant_habits_sign',
            field=models.BooleanField(default=False, help_text='Признак приятной привычки'),
        ),
        migrations.AlterField(
            model_name='habits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_lesson',
                                    to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
