# Generated by Django 5.2 on 2025-04-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habits_pleasant_habits_sign_alter_habits_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='tame',
            new_name='time',
        ),
    ]
