# Generated by Django 5.1.8 on 2025-04-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_award_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='name',
            field=models.CharField(blank=True, help_text='Название привычки', max_length=50, null=True),
        ),
    ]
