# Generated by Django 5.1.8 on 2025-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_habits_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
