# Generated by Django 5.1.8 on 2025-04-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_award_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='owner',
            new_name='user',
        ),
    ]
